/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#c6c6c7",
        "primary-fixed": "#fde400",
        "surface-tint": "#dec800",
        "tertiary-fixed-dim": "#ffb95c",
        "secondary-fixed": "#e2e2e2",
        "on-primary-container": "#716500",
        "inverse-on-surface": "#303030",
        "surface-variant": "#353535",
        "secondary": "#c6c6c7",
        "surface-container": "#1f1f1f",
        "surface-dim": "#131313",
        "on-secondary-fixed-variant": "#454747",
        "surface": "#131313",
        "on-tertiary-fixed": "#2a1700",
        "on-surface": "#e2e2e2",
        "inverse-primary": "#6a5f00",
        "inverse-surface": "#e2e2e2",
        "on-secondary-container": "#b4b5b5",
        "on-error": "#690005",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#504700",
        "primary": "#ffffff",
        "background": "#131313",
        "outline-variant": "#4b4731",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-low": "#1b1b1b",
        "on-secondary": "#2f3131",
        "on-surface-variant": "#cdc7aa",
        "primary-container": "#fde400",
        "primary-fixed-dim": "#dec800",
        "outline": "#979177",
        "error": "#ffb4ab",
        "on-primary-fixed": "#201c00",
        "on-primary": "#373100",
        "tertiary-fixed": "#ffddb7",
        "error-container": "#93000a",
        "on-tertiary-container": "#8d5900",
        "tertiary-container": "#ffddb7",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353535",
        "on-background": "#e2e2e2",
        "surface-bright": "#393939",
        "on-tertiary": "#462a00",
        "secondary-container": "#454747",
        "tertiary": "#ffffff",
        "brand-amber": "#FFA500",
        "brand-neon": "#00FF66",
        "brand-cyan": "#00E5FF"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "touch-target-min": "70px",
        "margin-mobile": "20px",
        "gutter-mobile": "16px",
        "stack-gap": "16px"
      },
      fontFamily: {
        "sans": ["'Atkinson Hyperlegible'", "'Inter'", "system-ui", "sans-serif"],
        "body-md": ["'Atkinson Hyperlegible'", "sans-serif"],
        "label-md": ["'Atkinson Hyperlegible'", "sans-serif"],
        "label-lg": ["'Atkinson Hyperlegible'", "sans-serif"],
        "body-lg": ["'Atkinson Hyperlegible'", "sans-serif"],
        "headline-lg": ["'Atkinson Hyperlegible'", "sans-serif"],
        "headline-md": ["'Atkinson Hyperlegible'", "sans-serif"]
      },
      borderWidth: {
        '3': '3px',
        '6': '6px',
      }
    },
  },
  plugins: [],
}
